### ISSUE TITLE
error during fetch()

### ISSUE THREAD

**Issue by windmaple** [charlierguo/gmail#29]
I'm getting this error when trying to fetch any msg. I'm at commit 667c14958714c5ea7b5487e79e262d40818229a4 and using ubuntu. Looks like a bug. Hopefully Charlie can fix it soon.

> > > unread[1].fetch()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "message.py", line 171, in fetch
> > >     self.parse(results[0])
> > >   File "message.py", line 164, in parse
> > >     self.attachments = [Attachment(attachment) for attachment in self.message._payload if attachment.get('Content-Disposition') is not None]
> > > AttributeError: 'str' object has no attribute 'get'

**Comment by windmaple** [comment]
btw, the msg body was actually fetch successfully. It's just the attachment part fails.
