### ISSUE TITLE
imcodebreaker 

### ISSUE THREAD

**Issue by Data-World** [charlierguo/gmail#81]
No module named 'utf'  
python3

**Comment by bitcoin4cashqc** [comment]
same here python 3.7.0 with py env:

`Traceback (most recent call last):
  File "main.py", line 31, in <module>
    import gmail
  File "/home/line/.pyenv/versions/3.7.0/lib/python3.7/site-packages/gmail-0.0.5-py3.7.egg/gmail/__init__.py", line 16, in <module>
  File "/home/line/.pyenv/versions/3.7.0/lib/python3.7/site-packages/gmail-0.0.5-py3.7.egg/gmail/gmail.py", line 5, in <module>
ModuleNotFoundError: No module named 'utf'
`
